[package]
name = "cyclotron-server"
version = "0.1.0"
authors = []

[dependencies]
cyclotron-backend = { path = "../backend"}
hyper = "0.11.18"
websocket = "0.20.2"
futures = "0.1.18"
serde = "1.0.27"
serde_derive = "1.0.27"
serde_json = "1.0.9"
docopt = "0.8.3"
failure = "0.1.1"
notify = "4.0.0"